### ISSUE TITLE
Missing prime check

### ISSUE THREAD

**Issue by ginnyfahs** [MrRogerino/dbc-whiteboarding#17]
https://github.com/MrRogerino/dbc-whiteboarding/blob/ba74ec4d2e978d72897ee4a67845703a9279a76d/August_3/example_solutions/prime_factorization.rb#L8

Hey Roger - I think a line is missing here. Don't we need to check that the divisor is prime before adding it to the prime hash?

**Comment by MrRogerino** [comment]
Nope! That's the beauty of using ```#find```. The first potential value that is non-prime is 4. However, the ```.find``` function will exit beforehand because anything that is divisible by 4 is already divisible by 2, which is prime. The same is true for all non-prime divisors.
